[tool.commitizen]
name = "cz_conventional_commits"
version = "1.2.3"
tag_format = "v$version"
version_files = [
    "client/VERSION",
    "client/pyproject.toml:^version",
    "client/loophost/__init__.py:^__version",
    ]